/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mariafernandaviloriazapata
 */

public class sim extends javax.swing.JFrame {
    
    public double ang, vo, co;
    public static double ang1, vo1, co1;
    public double tr;
    public double x, y;
    public static double[] posx, posy, vy;
    public double t;
    public double y2;
    public boolean j;
    DefaultTableModel mt = new DefaultTableModel();
    static DecimalFormat df = new DecimalFormat("#.##");
    int Et = 0;
    
    public sim() {
        this.setSize(1000, 800);
        this.setLocationRelativeTo(null);
        setTitle("FREE KICK");
        setIconImage(new ImageIcon(getClass().getResource("football.png")).getImage());
//        setLocationRelativeTo();
        initComponents();
        String ids[] = {"Tiempo(s)", "Posición x (m)", "Posición Y (m)", "Velocidad en Y (m/s)"};
        
        mt.setColumnIdentifiers(ids);
        
        table.setModel(mt);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Btp = new javax.swing.JButton();
        pelota = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingvo = new javax.swing.JTextField();
        anim = new javax.swing.JButton();
        ingang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        graficaxy = new javax.swing.JButton();
        graficaxy1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        resis = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btp.setText("Pausar");
        Btp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtpActionPerformed(evt);
            }
        });
        jPanel1.add(Btp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, 50));

        pelota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/pelota.png"))); // NOI18N
        jPanel1.add(pelota, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 100, 80));

        jLabel3.setText("Ángulo de inclinación:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 30));

        jLabel2.setText("Velocidad inicial (m/s):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 30));
        jPanel1.add(ingvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 100, 30));

        anim.setText("Animar");
        anim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animActionPerformed(evt);
            }
        });
        jPanel1.add(anim, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 80, 30));
        jPanel1.add(ingang, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 100, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        graficaxy.setText("Gráfica X vs Y");
        graficaxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficaxyActionPerformed(evt);
            }
        });
        jPanel1.add(graficaxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 130, 60));

        graficaxy1.setText("Gráfica V vs X");
        graficaxy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficaxy1ActionPerformed(evt);
            }
        });
        jPanel1.add(graficaxy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 130, 60));

        exit.setText("Borrar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 30));

        resis.setText("Resistencia del aire");
        resis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resisActionPerformed(evt);
            }
        });
        jPanel1.add(resis, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        table.setBackground(new java.awt.Color(51, 51, 51));
        table.setForeground(new java.awt.Color(51, 204, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 490, 1050, 240));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/cancha copy.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 540));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setForeground(new java.awt.Color(0, 102, 204));

        jTextField5.setBackground(new java.awt.Color(0, 102, 204));
        jTextField5.setText("Posición X");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(0, 102, 204));
        jTextField6.setText("Posición Y");
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(0, 102, 204));
        jTextField7.setText("Velocidad en Y");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(0, 102, 204));
        jTextField8.setText("Tiempo(s)");
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField5)
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(jTextField8)
                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1030, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animActionPerformed
        // TODO add your handling code here:
        try{
            ang = Double.parseDouble(ingang.getText());
            vo = Double.parseDouble(ingvo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si hay un error
        }
        if (ang < 0 || vo < 0 ) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores positivos.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }
        ang = Math.toRadians(180-ang);
        tr = 0;
        
        int arcx1 = 220;
        int arcy1 = 110;
        int arcy2 = 420;
        int arcx2 = 300;
        int i;
        t = (2*vo*Math.sin(ang))/9.8;
        boolean f = resis.isSelected();
        
        if (f == true) {
            Thread animation = new Thread(new Runnable() {
                @Override
                public void run() {
                    x = 850; 
                    y = 360; 

                    
                    while (tr <= t) {
                        
                        double newx = 850 + 2*posxfric(tr); 
                        double newy = 360 - 2*posyfric(tr);
                        

                        SwingUtilities.invokeLater(new Runnable() {
                            @Override
                            public void run() {
                                pelota.setLocation((int)newx, (int)newy);
                            }
                        });
  
                        
                        double vy = vo*Math.sin(ang);
                        double vy2 = vy -9.8*tr;


                        if ((newx >= arcx1 && newx<=arcx2) && (newy >= arcy1 && newy <= arcy2)){
                            JOptionPane.showMessageDialog(null, "¡La pelota ha entrado al arco!");
                            pelota.setLocation(850,360);
                            break;
                        } 
                        if (newy > 360){
                            
                            pelota.setLocation(850,360);
                        
                            break;
                        }
                        if (newy < 0){
                            
                            pelota.setLocation(850,360);
                            
                            break;
                        }

                        
                        
                        if (vo > 0 & ang > 0) {
                        mt.addRow(new Object[]{df.format(tr), df.format(-posx(tr)),df.format(posy(tr)), df.format(vy2)});
                        }
                        
                        try {
                            // Pausa para hacer la animación más fluida
                            Thread.sleep(15); 
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        if (Et%2==0){
                            tr += 0.1; 
                        }
                        
                    }
                    pelota.setLocation(850,360);
                }
            });
            animation.start(); // Iniciar el hilo de animación
        }else{
            pelota.setLocation(850,360);
            Thread animation = new Thread(new Runnable() {
                @Override
                public void run() {
                    x = 850; 
                    y = 360; 
                    y2 = 0;

                    // Bucle para animar
                    while (y2 <=y) {
                        
                        
                        double newx = 850 + 2*posx(tr); 
                        double newy = 360 - 2*posy(tr);
                        y2 = newy;

                        SwingUtilities.invokeLater(new Runnable() {
                            @Override
                            public void run() {
                                pelota.setLocation((int)newx, (int)newy);
                            }
                        });
                        
                        double vy = vo*Math.sin(ang);
                        double vy2 = vy -9.8*tr;

                        // Detener la animación si la pelota toca o pasa el suelo
                        if ((newx >= arcx1 && newx<=arcx2) && (newy >= arcy1 && newy <= arcy2)){
                            JOptionPane.showMessageDialog(null, "¡La pelota ha entrado al arco!");
                            pelota.setLocation(850,360);
                            break;
                        }
                        
                        if (newy > 430){
                            
                            pelota.setLocation(850,360);
                            break;
                        }
                        if (newy < 0){
                            
                            pelota.setLocation(850,360);
                            break;
                        }
                        
                        
                        mt.addRow(new Object[]{df.format(tr), df.format(-posx(tr)),df.format(posy(tr)), df.format(vy2)});
                        
                        try {
                            // Pausa para hacer la animación más fluida
                            Thread.sleep(20); 
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        if (Et%2==0){
                            tr += 0.1; 
                        }
                        
                    }
                    pelota.setLocation(850,360);
                }
            });
            animation.start();
        }
        
    }//GEN-LAST:event_animActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        inicio in = new inicio();
        in.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void graficaxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficaxyActionPerformed
        // TODO add your handling code here:
        Graficas g = new Graficas();
        ang1 = Double.parseDouble(ingang.getText());
        vo1 = Double.parseDouble(ingvo.getText());
        ang1 = Math.toRadians(180-ang);
        j = resis.isSelected();
        
    }//GEN-LAST:event_graficaxyActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        ingang.setText("");
        ingvo.setText("");
        pelota.setLocation(850,360);
        mt.getDataVector().removeAllElements();
        mt.fireTableDataChanged();
        
    }//GEN-LAST:event_exitActionPerformed

    private void graficaxy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficaxy1ActionPerformed
        // TODO add your handling code here:
        Grafica2 gr = new Grafica2();
        ang1 = Double.parseDouble(ingang.getText());
        vo1 = Double.parseDouble(ingvo.getText());
        ang1 = Math.toRadians(180-ang);
        j = resis.isSelected();
        
    }//GEN-LAST:event_graficaxy1ActionPerformed

    private void resisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resisActionPerformed

    private void BtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtpActionPerformed
        Et = Et+ 1;
        if (Et%2==1){
            Btp.setText("Renaudar");
        } else{
            Btp.setText("Pausar");
        }
    }//GEN-LAST:event_BtpActionPerformed
    public double posx(double t){
        
        return vo * Math.cos(ang) * t;
        
        
    }
    public double posy(double t) {
        double g = 9.8; 
        
        return (vo * t * Math.sin(ang)) - (0.5 * g * Math.pow(t, 2));
    }
    
    // Mejorar el uso de estas fórmulas.
    public double posxfric(double t) {
        double k = 0.5; // Coeficiente de fricción
        double vx = vo * Math.cos(ang);
        return vx*t - k*t*0.01;
        
    }
    public double posyfric(double t) {
        double g = 9.8;
        double k = 0.5;
        double vy = vo * Math.sin(ang) - 0.5*g*t*0.3;
        return vy *t - 0.5*g*Math.pow(t,2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
      }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sim().setVisible(true);
            }
        });
    }
    
    
    


        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btp;
    private javax.swing.JButton anim;
    private javax.swing.JButton exit;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton graficaxy;
    private javax.swing.JButton graficaxy1;
    public javax.swing.JTextField ingang;
    public javax.swing.JTextField ingvo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel pelota;
    private javax.swing.JRadioButton resis;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
